version: '3'

services:
  "3000":
    build:
      context: ./packages/3000
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./packages/3000:/app

